export const subcategoriesMap = {
  qida: [
    "Süd və süd məhsulları",
    "Ət və ət məhsulları",
    "Dəniz məhsulları",
    "Şirniyyat",
    "Un məmulatları",
    "Quru qidalar",
    "İçkilər",
    "Hazır yeməklər, Yarımfabrikatlar",
    "Digər",
  ],
  shexsibaxim: [
    "Dəri baxımı",
    "Ağız və diş baxımı məhsulları",
    "Qadın baxım məhsulları",
    "Dezodorant və Ətirlər",
    "Saç baxımı",
    "Gigiyena",
    "Üz və bədən baxımı",
    "Hamam məhsulları",
    "Digər",
  ],
  temizlikmehsullari: [
    "Paltaryuma məhsulları",
    "Səth təmizləmə məhsulları",
    "Otaq ətirləri",
    "Qabyuma məhsulları",
    "Digər",
  ],
  islamieshyavekitablar: [
    "Dini kitablar",
    "Səccadələr",
    "Təsbehlər",
    "Geyimlər",
    "Hədiyyəlik",
    "Digər",
  ],
  saglamliq: ["Dərman", "Qida əlavəsi", "Digər"],
  ushaqmehsullari: ["Uşaq qidaları", "Təmizlik vasitələri", "Digər"],
};
